=== Lilpookiemane/cjmcanal.github.io/NationalParks.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<!-- Root element -->
	<xs:element name="NationalParks">
		<xs:complexType>
			<xs:sequence>
				<xs:elmenet name="NationalPark" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name" type="xs:string"/>
							<xs:element name="Phone" type="xs:string" maxOccurs="unbounded"/>
							<xs:element name ="Address">
								<xs:complexType>
									<xs:sequence>
										<xs:element name ="Number" type="xs:string"/>
										<xs:element name ="Street" type="xs:string"/>
										<xs:element name ="City" type="xs:string"/>
										<xs:element name ="State" type="xs:string"/>
										<xs:element name ="Zip" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>		
						</xs:sequence>
						
						<!-- Attributes -->
						<xs:attribute name="NearestAirport" type="xs:string" use="required"/>
						<xs:attribute name="Rating" type="xs:decimal" use="optional"/>
								
						
					</xs:complexType>
				</xs:elmenet>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== Lilpookiemane/cjmcanal.github.io/NationalParksErrors.xml
<?xml version="1.0" encoding="utf-8"?>
<NationalParks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			   xsi:noNamespaceSchemaLocation="NationalParks.xsd">

	<!-- Wrong root element -->
	<NationalPar NearestAirport="Fresno" Rating="4.7">
		<Name>Yosemite</Name>
		<Phone>209-372-0200</Phone>
		<Address>
			<Number>9035</Number>
			<Street>Village Drive</Street>
			<City>Yosemite Valley</City>
			<State>CA</State>
			<Zip>95389</Zip>
		</Address>
	</NationalPark>

	<!-- Missing required attribute -->
		<NationalPark Rating="4.7">
			<Name>Yosemite</Name>
			<Phone>209-372-0200</Phone>
			<Address>
				<Number>9035</Number>
				<Street>Village Drive</Street>
				<City>Yosemite Valley</City>
				<Zip>95389</Zip>
			</Address>
		</NationalPark>

		<!-- Phone element is missing -->

		<NationalPark NearestAirport="El Paso" Rating="4.6">
			<Name>Carlsbad Caverns</Name>
			<Address>
				<Number>727</Number>
				<Street>Carlsbad Caverns Highway</Street>
				<City>Carlsbad</City>
				<State>NM</State>
				<Zip>88220</Zip>
			</Address>
		</NationalPark>

		<!-- Closing Address tag missing -->

		<NationalPark NearestAirport="Bozeman" Rating="4.9">
			<Name>Yellowstone</Name>
			<Phone>307-344-7381</Phone>
			<Address>
				<Number>2</Number>
				<Street>Grand Loop Road</Street>
				<City>Yellowstone National Park</City>
				<State>WY</State>
				<Zip>82190</Zip>
		</NationalPark>

		<!-- Two Name elements -->

		<NationalPark NearestAirport="Flagstaff">
			<Name>Petrified Forest</Name>
			<Name>Petrified Forest</Name>
			<Phone>928-524-6228</Phone>
			<Address>
				<Number>1</Number>
				<Street>Park Road</Street>
				<City>Petrified Forest National Park</City>
				<State>AZ</State>
				<Zip>86028</Zip>
			</Address>
		</NationalPark>
		
		
</NationalParks>

=== Lilpookiemane/cjmcanal.github.io/NationalParks.xml
<?xml version="1.0" encoding="utf-8"?>
<NationalParks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			   xsi:noNamespaceSchemaLocation="NationalParks.xsd">


	<NationalPark NearestAirport="Flagstaff" Rating="4.8">
		<Name>Grand Canyon</Name>
		<Phone>928-638-7496</Phone>
		<Phone>800-638-7496</Phone>
		<Address>
			<Number>8</Number>
			<Street>S Entrance Road</Street>
			<City>Grand Canyon</City>
			<State>AZ</State>
			<Zip>86023</Zip>
		</Address>
	</NationalPark>

	<NationalPark NearestAirport="Fresno" Rating="4.7">
		<Name>Yosemite</Name>
		<Phone>209-372-0200</Phone>
		<Address>
			<Number>9035</Number>
			<Street>Village Drive</Street>
			<City>Yosemite Valley</City>
			<State>CA</State>
			<Zip>95389</Zip>
		</Address>
	</NationalPark>

	<NationalPark NearestAirport="El Paso">
		<Name>White Sands</Name>
		<Phone>574-479-6124</Phone>
		<Address>
			<Number>19955</Number>
			<Street>US Highway 70</Street>
			<City>Alamogordo</City>
			<State>NM</State>
			<Zip>88310</Zip>
		</Address>
	</NationalPark>

	<NationalPark NearestAirport="Bozeman" Rating="4.9">
		<Name>Yellowstone</Name>
		<Phone>307-344-7381</Phone>
		<Address>
			<Number>2</Number>
			<Street>Grand Loop Road</Street>
			<City>Yellowstone National Park</City>
			<State>WY</State>
			<Zip>82190</Zip>
		</Address>
	</NationalPark>

	<NationalPark NearestAirport="El Paso" Rating="4.6">
		<Name>Carlsbad Caverns</Name>
		<Phone>575-785-2232</Phone>
		<Address>
			<Number>727</Number>
			<Street>Carlsbad Caverns Highway</Street>
			<City>Carlsbad</City>
			<State>NM</State>
			<Zip>88220</Zip>
		</Address>
	</NationalPark>

	<NationalPark NearestAirport="Flagstaff">
		<Name>Petrified Forest</Name>
		<Phone>928-524-6228</Phone>
		<Address>
			<Number>1</Number>
			<Street>Park Road</Street>
			<City>Petrified Forest National Park</City>
			<State>AZ</State>
			<Zip>86028</Zip>
		</Address>
	</NationalPark>

	<NationalPark NearestAirport="Buffalo" Rating="4.8">
		<Name>Niagra Falls</Name>
		<Phone>716-278-1796</Phone>
		<Address>
			<Number>6650</Number>
			<Street>Niagara Falls Blvd</Street>
			<City>Niagara Falls</City>
			<State>NY</State>
			<Zip>14304</Zip>
		</Address>
	</NationalPark>

	<NationalPark NearestAirport="Denver" Rating="4.7">
		<Name>Rocky Mountain</Name>
		<Phone>970-586-1206</Phone>
		<Address>
			<Number>100</Number>
			<Street>0.5 Miles South of Estes Park</Street>
			<City>Estes Park</City>
			<State>CO</State>
			<Zip>80517</Zip>
		</Address>
	</NationalPark>

	<NationalPark NearestAirport="Las Vegas">
		<Name>Zion</Name>
		<Phone>	435-772-3256</Phone>
		<Address>
			<Number>1</Number>
			<Street>Zion Park Blvd</Street>
			<City>Springdale</City>
			<State>UT</State>
			<Zip>84767</Zip>
		</Address>
	</NationalPark>

	<NationalPark NearestAirport="Las Vegas" Rating="4.9">
		<Name>Death Valley</Name>
		<Phone>760-786-3200</Phone>
		<Address>
			<Number>1</Number>
			<Street>Death Valley National Park</Street>
			<City>Death Valley</City>
			<State>CA</State>
			<Zip>92328</Zip>
		</Address>
	</NationalPark>

</NationalParks>
